# Generated by Django 3.2.4 on 2021-06-30 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndWiki', '0002_peoples_recaps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='peoples',
            new_name='People',
        ),
        migrations.RenameModel(
            old_name='recaps',
            new_name='Recap',
        ),
    ]
