# Generated by Django 3.2.4 on 2021-06-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndWiki', '0003_auto_20210629_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='description',
            field=models.TextField(default='Enter Description here'),
        ),
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='description',
            field=models.TextField(default='Enter Description here'),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='race',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recap',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recap',
            name='description',
            field=models.TextField(default='Enter Description here'),
        ),
    ]
