# Generated by Django 3.2.4 on 2021-06-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndWiki', '0005_alter_recap_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ('type',)},
        ),
    ]
